#NAME: Devyan Biswas
#EMAIL: devyanbiswas@outlook.com
#ID: #UID

defualt:
	rm -f lab3b
	ln runLab3B lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-#UID.tar.gz fsCheck.py README Makefile runLab3B

clean:
	rm -f lab3b-#UID.tar.gz lab3b *~
