#NAME: Devyan Biswas
#EMAIL: devyanbiswas@outlook.com
#ID: 804988161

defualt:
	rm -f lab3b
	ln runLab3B lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-804988161.tar.gz fsCheck.py README Makefile runLab3B

clean:
	rm -f lab3b-804988161.tar.gz lab3b *~
