#NAME: Devyan Biswas
#EMAIL: devyanbiswas@gmail.com
#ID: #UID

.SILENT:

default:
	gcc -Wall -Wextra -o lab3a fsInfo.c
dist:
	tar -czvf lab3a-#UID.tar.gz fsInfo.c ext2_fs.h Makefile README
clean:
	rm -f lab3a lab3a-#UID.tar.gz *~ *#
